# $Id: Makefile 19106 2009-01-23 14:56:32Z hmitonneau $
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=dialog_acc.so
LIBS= $(RADIUS_LIB)

include ../../Makefile.modules

