# $Id$
#
# Content-Encoding operations module for OpenSIPs
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=content_encoding.so

LIBS=-lz

include ../../Makefile.modules
